### ISSUE TITLE
Disconnected from device

### ISSUE THREAD

**Issue by sudeshnb** [rans-rans/all_bluetooth#1]
E/flutter (29833): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method permit on channel method_channel)
E/flutter (29833): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)

**Comment by Shiba3006** [comment]
same happened with me

**Comment by rans-rans** [comment]
the permit method isn't part of the package. the PERMIT method was created in the example project just to help with handling permissions instead of installing another package. it implementation will only work for the example project and if you look inside the MainActivity.kt in the android folder in the example folder, you will see its implementation and how it is handled.

For a real project, please use a package like [permission_handler](https://pub.dev/packages/permission_handler) to request for permissions.
